## DO NOT EDIT THIS FILE ##
## THIS IS THE MAIN FILE TO RUN THE WHOLE PIPELINE ##
## IT SHOULD RUN AS IS AND WORK FINE IF ALL OTHER FILES ARE CORRECT ##

import json, os
from datetime import datetime, UTC
from pipeline.data import load_data
from pipeline.preprocess import preprocess
from pipeline.model import train_model
from pipeline.evaluate import evaluate
from pipeline.visualize import make_plots

def main(seed: int = 42, outdir: str = "outputs"):
    os.makedirs(outdir, exist_ok=True)
    df = load_data()                                    # These are the functions that needs to improved, each student for each group should take care of one part
    X_train, X_test, y_train, y_test, preproc = preprocess(df)   # These are the functions that needs to improved, each student for each group should take care of one part
    model = train_model(X_train, y_train, preproc=preproc, seed=seed)    # These are the functions that needs to improved, each student for each group should take care of one part
    metrics = evaluate(model, X_test, y_test)           # These are the functions that needs to improved, each student for each group should take care of one part
    make_plots(model, X_test, y_test, df, outdir)       # These are the functions that needs to improved, each student for each group should take care of one part

    metrics["timestamp"] = datetime.now(UTC).isoformat() + "Z"
    with open(os.path.join(outdir, "metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)
    print("Done. Metrics saved to outputs/metrics.json")

if __name__ == "__main__":
    main()